<?php

// Generate keys
// 	Follow setup.txt instructions
//	$ php step0.php

// Register your application
//	"Register Application" on https://core.braveineve.com/application/manage/
//	Paste public key generated by step0.php under "ECDSA Key"

// --------------------------------------------

// Define the core API endpoint to use
$cfg_endpoint = 'https://core.braveineve.com/api';

// Extract ID encoded into your app url on https://core.braveineve.com/application/manage/
$cfg_app_id = '';

// Paste public key generated by step0.php
$cfg_pubkey = '';

// Paste private key generated by step0.php
$cfg_privkey = '';

// URL to redirect on successfull core auth
$cfg_url_success = 'http://example.com/step2.php';

// URL to redirect on failed core auth
$cfg_url_failure = 'http://example.com/fail.php';

?>
