<?php

// Generate keys
// 	Follow setup.txt instructions
//	$ php step0.php

// Register your application
//	"Register Application" on https://core.braveineve.com/application/manage/
//	Paste public key generated by step0.php under "ECDSA Key"

// --------------------------------------------

// Extract ID encoded into your app url on https://core.braveineve.com/application/manage/
$application_id = '';

// Paste public key generated by step0.php
$public_key = '';

// Paste private key generated by step0.php
$private_key = '';

?>
