<?php

// Generate keys
// 	Follow setup.txt instructions
//	$ php step0.php

// Register your application
//	"Register Application" on https://core.braveineve.com/application/manage/
//	Paste public key generated by step0.php under "ECDSA Key"

// --------------------------------------------

// Paste private key generated by step0.php
$private_key = '';

// Extract ID encoded into your app url on https://core.braveineve.com/application/manage/
$application_id = '';

// This is NOT your step0 generated key!
// Select your application on https://core.braveineve.com/application/manage/
// Core will present you a hexencoded public key
$public_key = '';

?>
